# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0006_auto_20160318_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoarding',
            name='area',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='available_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='codes.Category'),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='elevation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='facing_from',
            field=models.CharField(blank=True, default=b'Not Available', max_length=200),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='facing_to',
            field=models.CharField(blank=True, default=b'Not Available', max_length=200),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='hoarding_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='codes.OutdoorType'),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='landmark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='price_per_month',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
